ALTER TABLE leads 
  ADD COLUMN IF NOT EXISTS order_number SERIAL,
  ADD COLUMN IF NOT EXISTS order_total DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS payment_status VARCHAR(20) DEFAULT 'unpaid',
  ADD COLUMN IF NOT EXISTS payment_method VARCHAR(20) DEFAULT '',
  ADD COLUMN IF NOT EXISTS internal_notes TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS tracking_id VARCHAR(100) DEFAULT '',
  ADD COLUMN IF NOT EXISTS unit_price DECIMAL(10,2) DEFAULT 0;

ALTER TABLE tenant_settings
  ADD COLUMN IF NOT EXISTS business_address TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS business_phone VARCHAR(20) DEFAULT '',
  ADD COLUMN IF NOT EXISTS business_email VARCHAR(100) DEFAULT '';
